# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [1]:
import numpy as np

#### 2. Print your NumPy version.

In [5]:
print(np.__version__)

1.19.2


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [7]:
a = np.random.random((2, 3, 5))
print(a)

[[[0.66478229 0.19223991 0.34724699 0.36570846 0.03723988]
  [0.90817162 0.70634593 0.54029128 0.73130462 0.62827854]
  [0.71941247 0.64642019 0.67693662 0.60032403 0.03816821]]

 [[0.95508203 0.84255082 0.99289421 0.24472519 0.28383218]
  [0.0998398  0.17070922 0.89513899 0.85226016 0.50150635]
  [0.13587871 0.69663547 0.33696297 0.26344983 0.50812898]]]


In [10]:
a = np.random.randint(10, size = (2, 3, 5))
print(a)

[[[1 7 2 1 9]
  [9 8 9 4 2]
  [5 9 6 2 2]]

 [[2 7 7 6 3]
  [8 1 4 3 6]
  [8 1 9 5 3]]]


In [11]:
a = np.random.rand(2, 3, 5)
print(a)

[[[1.58499829e-01 5.19949228e-01 1.13728587e-01 1.45035733e-01
   7.77543613e-01]
  [5.74949973e-01 2.05150420e-01 2.36015660e-01 4.18024604e-01
   5.00188861e-01]
  [4.27369851e-01 9.08407961e-01 5.02066745e-02 8.35031253e-02
   8.84458430e-02]]

 [[3.41228687e-01 6.64317042e-01 5.07726158e-01 5.89426695e-01
   3.83524874e-01]
  [9.96674570e-01 7.02487342e-01 8.29953325e-01 8.62469171e-05
   2.88503988e-01]
  [9.82141715e-01 6.96418381e-01 9.44644276e-01 3.66865330e-01
   4.50494694e-01]]]


In [16]:
a = np.random.choice([10, 3, 4, 9, 21, 35], size=(2, 3, 5))
print(a)

[[[ 9 21 10 21 35]
  [ 9 21 21  9  3]
  [ 9  9  9  9 35]]

 [[10 21  9  9 10]
  [21  4 10  9 10]
  [10  4 21  9  4]]]


#### 4. Print *a*.


In [ ]:
# your code here

#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [13]:
b = np.ones((5, 2, 3))

#### 6. Print *b*.


In [14]:
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [17]:
a.size == b.size

True

#### 8. Are you able to add *a* and *b*? Why or why not?


In [19]:
np.add(a, b)

# it is not possible to add them because although they are the same size, they have different shape.
# to add 2 numpy arrays, they must be the same shape

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [26]:
c = np.reshape(b, (2, 3, 5))
print(c)

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [28]:
d = np.add(a, c)

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [33]:
print(a)
print('\n')
print(d)
# every values in d is now 1 unit higher than those in a. This is due to the effect of summing a with c, the latter being an array of 1s

[[[ 9 21 10 21 35]
  [ 9 21 21  9  3]
  [ 9  9  9  9 35]]

 [[10 21  9  9 10]
  [21  4 10  9 10]
  [10  4 21  9  4]]]


[[[10. 22. 11. 22. 36.]
  [10. 22. 22. 10.  4.]
  [10. 10. 10. 10. 36.]]

 [[11. 22. 10. 10. 11.]
  [22.  5. 11. 10. 11.]
  [11.  5. 22. 10.  5.]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [34]:
e = np.multiply(a, c)

#### 13. Does *e* equal to *a*? Why or why not?


In [35]:
print(a)
print('\n')
print(e)

[[[ 9 21 10 21 35]
  [ 9 21 21  9  3]
  [ 9  9  9  9 35]]

 [[10 21  9  9 10]
  [21  4 10  9 10]
  [10  4 21  9  4]]]


[[[ 9. 21. 10. 21. 35.]
  [ 9. 21. 21.  9.  3.]
  [ 9.  9.  9.  9. 35.]]

 [[10. 21.  9.  9. 10.]
  [21.  4. 10.  9. 10.]
  [10.  4. 21.  9.  4.]]]


#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [40]:
print(d)
d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)

[[[10. 22. 11. 22. 36.]
  [10. 22. 22. 10.  4.]
  [10. 10. 10. 10. 36.]]

 [[11. 22. 10. 10. 11.]
  [22.  5. 11. 10. 11.]
  [11.  5. 22. 10.  5.]]]


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [46]:
f = np.empty((2, 3, 5))
print(f)

[[[10. 22. 11. 22. 36.]
  [10. 22. 22. 10.  4.]
  [10. 10. 10. 10. 36.]]

 [[11. 22. 10. 10. 11.]
  [22.  5. 11. 10. 11.]
  [11.  5. 22. 10.  5.]]]


#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [50]:
for i in range(2):
    for j in range(3):
        for k in range(5):
            if d[i][j][k] > d_min and d[i][j][k] < d_mean:
                f[i][j][k] = 25
            if d[i][j][k] < d_max and d[i][j][k] > d_mean:
                f[i][j][k] = 75
            if d[i][j][k] == d_mean:
                f[i][j][k] = 50
            if d[i][j][k] == d_min:
                f[i][j][k] = 0
            if d[i][j][k] == d_max:
                f[i][j][k] = 100

#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [53]:
print(d)
print('\n')
print(f)

[[[10. 22. 11. 22. 36.]
  [10. 22. 22. 10.  4.]
  [10. 10. 10. 10. 36.]]

 [[11. 22. 10. 10. 11.]
  [22.  5. 11. 10. 11.]
  [11.  5. 22. 10.  5.]]]


[[[ 25.  75.  25.  75. 100.]
  [ 25.  75.  75.  25.   0.]
  [ 25.  25.  25.  25. 100.]]

 [[ 25.  75.  25.  25.  25.]
  [ 75.  25.  25.  25.  25.]
  [ 25.  25.  75.  25.  25.]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [55]:
f = np.empty((2, 3, 5), dtype='U1')
for i in range(2):
    for j in range(3):
        for k in range(5):
            if d[i][j][k] > d_min and d[i][j][k] < d_mean:
                f[i][j][k] = 'B'
            if d[i][j][k] < d_max and d[i][j][k] > d_mean:
                f[i][j][k] = 'D'
            if d[i][j][k] == d_mean:
                f[i][j][k] = 'C'
            if d[i][j][k] == d_min:
                f[i][j][k] = 'A'
            if d[i][j][k] == d_max:
                f[i][j][k] = 'E'
print(d)
print('\n')
print(f)

[[[10. 22. 11. 22. 36.]
  [10. 22. 22. 10.  4.]
  [10. 10. 10. 10. 36.]]

 [[11. 22. 10. 10. 11.]
  [22.  5. 11. 10. 11.]
  [11.  5. 22. 10.  5.]]]


[[['B' 'D' 'B' 'D' 'E']
  ['B' 'D' 'D' 'B' 'A']
  ['B' 'B' 'B' 'B' 'E']]

 [['B' 'D' 'B' 'B' 'B']
  ['D' 'B' 'B' 'B' 'B']
  ['B' 'B' 'D' 'B' 'B']]]
